# Generated by Django 5.2.8 on 2025-11-17 11:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("students", "0002_attendancerecord_transcript"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "late_fee_applied",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("card", "Debit/Credit Card"),
                            ("online", "Online Payment"),
                            ("upi", "UPI"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "db_table": "finance_payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.RemoveField(
            model_name="feepayment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="feepayment",
            name="fee_structure",
        ),
        migrations.RemoveField(
            model_name="feepayment",
            name="student",
        ),
        migrations.RemoveField(
            model_name="feepayment",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="updated_by",
        ),
        migrations.AlterModelOptions(
            name="feestructure",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="feestructure",
            name="fee_structu_categor_d88f08_idx",
        ),
        migrations.RenameField(
            model_name="feestructure",
            old_name="amount",
            new_name="total_amount",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="total_amount",
            new_name="amount_due",
        ),
        migrations.RenameIndex(
            model_name="feestructure",
            new_name="finance_fee_code_d9401a_idx",
            old_name="fee_structu_code_cbc284_idx",
        ),
        migrations.RemoveField(
            model_name="feestructure",
            name="category",
        ),
        migrations.RemoveField(
            model_name="feestructure",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="feestructure",
            name="late_fee",
        ),
        migrations.RemoveField(
            model_name="feestructure",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="feestructure",
            name="year",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="paid_date",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="title",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="feestructure",
            name="academic_year",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="components",
            field=models.JSONField(
                default=dict,
                help_text="Fee components as JSON: {'tuition': 5000, 'lab': 500, 'library': 100}",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="installment_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Installment rules: {'enabled': true, 'count': 3, 'schedule': [...]}",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="late_fee_policy",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Late fee policy: {'percentage': 5, 'flat_fee': 100, 'grace_days': 7}",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="academic_year",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="fee_components",
            field=models.JSONField(
                default=dict,
                help_text="Breakdown of fees: {'tuition': 5000, 'lab': 500}",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="fee_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="finance.feestructure",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="late_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="semester",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partially Paid"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="program",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Program name (e.g., 'Computer Science BS')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="semester",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="students.student",
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["program"], name="finance_fee_program_2bf0ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["is_active"], name="finance_fee_is_acti_28035c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="finance_inv_invoice_dd3aad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["student"], name="finance_inv_student_25a218_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="finance_inv_status_7c9653_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="finance_inv_due_dat_58b34d_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="feestructure",
            table="finance_fee_structures",
        ),
        migrations.AlterModelTable(
            name="invoice",
            table="finance_invoices",
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="students.student",
            ),
        ),
        migrations.DeleteModel(
            name="FeePayment",
        ),
        migrations.DeleteModel(
            name="Receipt",
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["receipt_number"], name="finance_pay_receipt_0d0a89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["invoice"], name="finance_pay_invoice_e4df34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["student"], name="finance_pay_student_9d2bb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="finance_pay_payment_0dd4d1_idx"
            ),
        ),
    ]
