"""
Reports Custom Managers and QuerySets
"""
from django.db import models
from django.utils import timezone


class ReportTemplateManager(models.Manager):
    """Manager for ReportTemplate model"""
    
    def active(self):
        """Get active report templates"""
        return self.filter(is_active=True)
    
    def by_category(self, category):
        """Get templates by category"""
        return self.filter(category=category, is_active=True)
    
    def public(self):
        """Get public templates"""
        return self.filter(is_public=True, is_active=True)
    
    def for_user(self, user):
        """Get templates accessible by user"""
        if user.is_staff or user.is_superuser:
            return self.active()
        
        # Get user roles
        user_roles = []
        if hasattr(user, 'student'):
            user_roles.append('student')
        if hasattr(user, 'faculty'):
            user_roles.append('faculty')
        if user.is_staff:
            user_roles.append('admin')
        
        # Filter by roles
        return self.filter(
            models.Q(is_public=True) | 
            models.Q(roles_allowed__contains=user_roles),
            is_active=True
        ).distinct()
    
    def schedulable(self):
        """Get schedulable templates"""
        return self.filter(is_scheduled=True, is_active=True)


class GeneratedReportManager(models.Manager):
    """Manager for GeneratedReport model"""
    
    def completed(self):
        """Get completed reports"""
        return self.filter(status='completed')
    
    def pending(self):
        """Get pending reports"""
        return self.filter(status='pending')
    
    def failed(self):
        """Get failed reports"""
        return self.filter(status='failed')
    
    def for_user(self, user):
        """Get reports generated by user"""
        return self.filter(generated_by=user)
    
    def not_expired(self):
        """Get non-expired reports"""
        now = timezone.now()
        return self.filter(
            models.Q(expires_at__isnull=True) | 
            models.Q(expires_at__gt=now),
            is_archived=False
        )
    
    def expired(self):
        """Get expired reports"""
        now = timezone.now()
        return self.filter(
            expires_at__lte=now,
            is_archived=False
        )
    
    def by_template(self, template):
        """Get reports by template"""
        return self.filter(template=template)
