# Generated by Django 5.2.8 on 2025-12-10 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0002_initial"),
        ("authentication", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        db_index=True, default="", max_length=20, unique=True
                    ),
                ),
                ("admission_year", models.IntegerField(db_index=True, default=2024)),
                (
                    "program",
                    models.CharField(db_index=True, default="", max_length=100),
                ),
                ("batch", models.CharField(default="", max_length=50)),
                ("section", models.CharField(blank=True, default="", max_length=10)),
                ("guardian_name", models.CharField(default="", max_length=200)),
                ("guardian_phone", models.CharField(default="", max_length=20)),
                (
                    "guardian_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("guardian_relation", models.CharField(default="", max_length=50)),
                (
                    "emergency_contact_name",
                    models.CharField(default="", max_length=200),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(default="", max_length=20),
                ),
                (
                    "student_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("graduated", "Graduated"),
                            ("withdrawn", "Withdrawn"),
                            ("suspended", "Suspended"),
                            ("expelled", "Expelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_record",
                        to="admissions.application",
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "ordering": ["student_id"],
            },
            bases=("authentication.user",),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "program",
                    models.CharField(db_index=True, default="", max_length=100),
                ),
                ("batch", models.CharField(default="", max_length=50)),
                ("section", models.CharField(blank=True, default="", max_length=10)),
                ("start_date", models.DateField(db_index=True)),
                ("expected_end_date", models.DateField(blank=True, null=True)),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "enrollment_data",
                    models.JSONField(
                        default=dict, help_text="Additional enrollment information"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to="admissions.application",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["student", "status"],
                        name="enrollments_student_929bef_idx",
                    ),
                    models.Index(
                        fields=["program", "batch"],
                        name="enrollments_program_0fa205_idx",
                    ),
                ],
                "unique_together": {("student", "program", "start_date")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_date", models.DateField()),
                ("session_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        max_length=20,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendance_records",
                        to="courses.course",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendance_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_attendance_records",
                "ordering": ["-session_date"],
                "indexes": [
                    models.Index(
                        fields=["student"], name="student_att_student_50b4d8_idx"
                    ),
                    models.Index(
                        fields=["course"], name="student_att_course__f8f3c2_idx"
                    ),
                    models.Index(
                        fields=["session_date"], name="student_att_session_1c1c36_idx"
                    ),
                ],
                "unique_together": {("student", "course", "session_date")},
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade_records_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="JSON snapshot of all finalized grade records",
                    ),
                ),
                ("total_credits_attempted", models.IntegerField(default=0)),
                ("total_credits_earned", models.IntegerField(default=0)),
                (
                    "cumulative_gpa",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transcript_type",
                    models.CharField(
                        choices=[
                            ("official", "Official Transcript"),
                            ("unofficial", "Unofficial Transcript"),
                            ("interim", "Interim Transcript"),
                        ],
                        default="unofficial",
                        max_length=50,
                    ),
                ),
                ("academic_year", models.CharField(blank=True, max_length=20)),
                ("semester", models.CharField(blank=True, max_length=50)),
                ("is_certified", models.BooleanField(default=False)),
                ("certification_date", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_transcripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "transcripts",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["student"], name="transcripts_student_043f1e_idx"
                    ),
                    models.Index(
                        fields=["transcript_type"],
                        name="transcripts_transcr_54bfec_idx",
                    ),
                    models.Index(
                        fields=["generated_at"], name="transcripts_generat_e01475_idx"
                    ),
                ],
            },
        ),
    ]
