# Generated by Django 5.2.8 on 2025-11-16 12:15

import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        db_index=True, default="", max_length=20, unique=True
                    ),
                ),
                ("admission_year", models.IntegerField(db_index=True, default=2024)),
                (
                    "program",
                    models.CharField(db_index=True, default="", max_length=100),
                ),
                ("batch", models.CharField(default="", max_length=50)),
                ("section", models.CharField(blank=True, default="", max_length=10)),
                ("guardian_name", models.CharField(default="", max_length=200)),
                ("guardian_phone", models.CharField(default="", max_length=20)),
                (
                    "guardian_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("guardian_relation", models.CharField(default="", max_length=50)),
                (
                    "emergency_contact_name",
                    models.CharField(default="", max_length=200),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(default="", max_length=20),
                ),
                (
                    "student_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("graduated", "Graduated"),
                            ("withdrawn", "Withdrawn"),
                            ("suspended", "Suspended"),
                            ("expelled", "Expelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_record",
                        to="admissions.application",
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "ordering": ["student_id"],
            },
            bases=("authentication.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "program",
                    models.CharField(db_index=True, default="", max_length=100),
                ),
                ("batch", models.CharField(default="", max_length=50)),
                ("section", models.CharField(blank=True, default="", max_length=10)),
                ("start_date", models.DateField(db_index=True)),
                ("expected_end_date", models.DateField(blank=True, null=True)),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "enrollment_data",
                    models.JSONField(
                        default=dict, help_text="Additional enrollment information"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to="admissions.application",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["student", "status"],
                        name="enrollments_student_929bef_idx",
                    ),
                    models.Index(
                        fields=["program", "batch"],
                        name="enrollments_program_0fa205_idx",
                    ),
                ],
                "unique_together": {("student", "program", "start_date")},
            },
        ),
    ]
