# Generated by Django 5.2.8 on 2025-11-16 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_date", models.DateField()),
                ("session_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        max_length=20,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="courses.course",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_records",
                "ordering": ["-session_date"],
                "indexes": [
                    models.Index(
                        fields=["student"], name="attendance__student_8ea8b5_idx"
                    ),
                    models.Index(
                        fields=["course"], name="attendance__course__9f4748_idx"
                    ),
                    models.Index(
                        fields=["session_date"], name="attendance__session_b87996_idx"
                    ),
                ],
                "unique_together": {("student", "course", "session_date")},
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade_records_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="JSON snapshot of all finalized grade records",
                    ),
                ),
                ("total_credits_attempted", models.IntegerField(default=0)),
                ("total_credits_earned", models.IntegerField(default=0)),
                (
                    "cumulative_gpa",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transcript_type",
                    models.CharField(
                        choices=[
                            ("official", "Official Transcript"),
                            ("unofficial", "Unofficial Transcript"),
                            ("interim", "Interim Transcript"),
                        ],
                        default="unofficial",
                        max_length=50,
                    ),
                ),
                ("academic_year", models.CharField(blank=True, max_length=20)),
                ("semester", models.CharField(blank=True, max_length=50)),
                ("is_certified", models.BooleanField(default=False)),
                ("certification_date", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_transcripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "transcripts",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["student"], name="transcripts_student_043f1e_idx"
                    ),
                    models.Index(
                        fields=["transcript_type"],
                        name="transcripts_transcr_54bfec_idx",
                    ),
                    models.Index(
                        fields=["generated_at"], name="transcripts_generat_e01475_idx"
                    ),
                ],
            },
        ),
    ]
