# Generated by Django 5.2.8 on 2025-11-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("authentication", "0001_initial"),
        ("admissions", "0001_initial"),
        ("courses", "0001_initial"),
        ("finance", "0002_payment_remove_feepayment_created_by_and_more"),
    ]

    operations = [
        # Indexes for authentication.User model
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_user_email ON users(email);
                CREATE INDEX IF NOT EXISTS idx_user_username ON users(username);
                CREATE INDEX IF NOT EXISTS idx_user_is_active ON users(is_active);
                CREATE INDEX IF NOT EXISTS idx_user_created_at ON users(created_at);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_user_email;
                DROP INDEX IF EXISTS idx_user_username;
                DROP INDEX IF EXISTS idx_user_is_active;
                DROP INDEX IF EXISTS idx_user_created_at;
            """
        ),
        
        # Indexes for admissions.Application model
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_application_status ON applications(status);
                CREATE INDEX IF NOT EXISTS idx_application_email ON applications(email);
                CREATE INDEX IF NOT EXISTS idx_application_program ON applications(program);
                CREATE INDEX IF NOT EXISTS idx_application_submitted_at ON applications(submitted_at);
                CREATE INDEX IF NOT EXISTS idx_application_created_at ON applications(created_at);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_application_status;
                DROP INDEX IF EXISTS idx_application_email;
                DROP INDEX IF EXISTS idx_application_program;
                DROP INDEX IF EXISTS idx_application_submitted_at;
                DROP INDEX IF EXISTS idx_application_created_at;
            """
        ),
        
        # Indexes for courses.Course model
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_course_status ON courses(status);
                CREATE INDEX IF NOT EXISTS idx_course_code ON courses(code);
                CREATE INDEX IF NOT EXISTS idx_course_created_at ON courses(created_at);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_course_status;
                DROP INDEX IF EXISTS idx_course_code;
                DROP INDEX IF EXISTS idx_course_created_at;
            """
        ),
        
        # Indexes for finance.Invoice model
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_invoice_status ON finance_invoices(status);
                CREATE INDEX IF NOT EXISTS idx_invoice_due_date ON finance_invoices(due_date);
                CREATE INDEX IF NOT EXISTS idx_invoice_created_at ON finance_invoices(created_at);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_invoice_status;
                DROP INDEX IF EXISTS idx_invoice_due_date;
                DROP INDEX IF EXISTS idx_invoice_created_at;
            """
        ),
        
        # Indexes for finance.Payment model
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_payment_timestamp ON finance_payments(payment_date);
                CREATE INDEX IF NOT EXISTS idx_payment_method ON finance_payments(method);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_payment_timestamp;
                DROP INDEX IF EXISTS idx_payment_method;
            """
        ),
        
        # Full-text search indexes for PostgreSQL
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_user_search ON users 
                    USING GIN (to_tsvector('english', coalesce(username,'') || ' ' || coalesce(email,'') || ' ' || coalesce(first_name,'') || ' ' || coalesce(last_name,'')));
                
                CREATE INDEX IF NOT EXISTS idx_course_search ON courses 
                    USING GIN (to_tsvector('english', coalesce(title,'') || ' ' || coalesce(code,'') || ' ' || coalesce(description,'')));
                
                CREATE INDEX IF NOT EXISTS idx_application_search ON applications 
                    USING GIN (to_tsvector('english', coalesce(first_name,'') || ' ' || coalesce(last_name,'') || ' ' || coalesce(email,'') || ' ' || coalesce(program,'')));
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_user_search;
                DROP INDEX IF EXISTS idx_course_search;
                DROP INDEX IF EXISTS idx_application_search;
            """
        ),
    ]

