# Generated by Django 5.2.8 on 2025-12-10 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sequence_order", models.IntegerField(default=0)),
                ("content", models.TextField(blank=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("link", "External Link"),
                            ("mixed", "Mixed Content"),
                        ],
                        default="text",
                        max_length=50,
                    ),
                ),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "course_modules",
                "ordering": ["course", "sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True)),
                (
                    "files",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of file paths/URLs for submitted files",
                    ),
                ),
                (
                    "grade_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("graded", "Graded"),
                            ("returned", "Returned to Student"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("is_late", models.BooleanField(default=False)),
                (
                    "late_penalty_applied",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage penalty applied",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "db_table": "submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("syllabus", models.TextField(blank=True)),
                ("credits", models.IntegerField(default=3)),
                (
                    "prerequisites",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of prerequisite course UUIDs",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("semester", models.CharField(blank=True, max_length=50)),
                ("academic_year", models.CharField(blank=True, max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "courses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("instructions", models.TextField(blank=True)),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
                ),
                ("grading_rubric", models.JSONField(blank=True, default=dict)),
                ("due_date", models.DateTimeField()),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("late_submission_allowed", models.BooleanField(default=True)),
                (
                    "late_penalty_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Percentage penalty per day for late submissions",
                        max_digits=5,
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("homework", "Homework"),
                            ("quiz", "Quiz"),
                            ("exam", "Exam"),
                            ("project", "Project"),
                            ("lab", "Lab Work"),
                        ],
                        default="homework",
                        max_length=50,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "assignments",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="GradeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Numeric grade (e.g., 85.50)",
                        max_digits=5,
                    ),
                ),
                (
                    "grade_letter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D", "D"),
                            ("F", "F"),
                            ("I", "Incomplete"),
                            ("W", "Withdrawn"),
                            ("P", "Pass"),
                            ("NP", "No Pass"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "grade_points",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grade points for GPA calculation (e.g., 4.00)",
                        max_digits=3,
                    ),
                ),
                ("finalized", models.BooleanField(default=False)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                ("semester", models.CharField(blank=True, max_length=50)),
                ("academic_year", models.CharField(blank=True, max_length=20)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_records",
                        to="courses.course",
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finalized_grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "grade_records",
                "ordering": ["-created_at"],
            },
        ),
    ]
