# Generated by Django 5.2.8 on 2025-12-10 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="graderecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_records",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="courses.assignment",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="students.student",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["code"], name="courses_code_fa42f1_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["status"], name="courses_status_67f368_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["created_by"], name="courses_created_417ade_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["course"], name="assignments_course__383e45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["due_date"], name="assignments_due_dat_708d3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graderecord",
            index=models.Index(
                fields=["course"], name="grade_recor_course__f5f47e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graderecord",
            index=models.Index(
                fields=["student"], name="grade_recor_student_aa3a78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graderecord",
            index=models.Index(
                fields=["finalized"], name="grade_recor_finaliz_1f42c6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="graderecord",
            unique_together={("course", "student", "semester", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["course", "sequence_order"],
                name="course_modu_course__81c696_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="module",
            unique_together={("course", "sequence_order")},
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["assignment"], name="submissions_assignm_9eeb28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["student"], name="submissions_student_51a963_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["grade_status"], name="submissions_grade_s_d9d9e7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("assignment", "student")},
        ),
    ]
