# Generated by Django 5.2.8 on 2025-12-06 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0002_alter_calendar_options_alter_category_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ukid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=False)),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, help_text="JSON configuration for the layout"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_layouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Layout",
                "verbose_name_plural": "Calendar Layouts",
                "ordering": ["-active", "name"],
            },
        ),
    ]
