# Generated by Django 5.2.8 on 2025-12-06 05:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ukid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("registration_number", models.BigIntegerField(unique=True)),
                ("roll_number", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=50)),
                ("enrollment_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "students",
                "ordering": ["first_name", "last_name"],
                "indexes": [
                    models.Index(fields=["email"], name="students_email_b942ac_idx"),
                    models.Index(
                        fields=["registration_number"],
                        name="students_registr_f0f54d_idx",
                    ),
                    models.Index(
                        fields=["is_active", "enrollment_date"],
                        name="students_is_acti_4b0538_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ukid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("program", models.CharField(max_length=100)),
                ("batch", models.CharField(max_length=6)),
                ("section", models.CharField(max_length=10)),
                ("semester", models.CharField(max_length=20)),
                ("enrollment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                            ("suspended", "Suspended"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ukid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_proof", "ID Proof"),
                            ("birth_cert", "Birth Certificate"),
                            ("transcript", "Academic Transcript"),
                            ("photo", "Photograph"),
                            ("medical", "Medical Certificate"),
                            ("transfer", "Transfer Certificate"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("file", models.FileField(upload_to="student_documents/")),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AcademicRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ukid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("semester", models.CharField(max_length=20)),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=4)),
                ("total_credits", models.IntegerField()),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_records",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "db_table": "academic_records",
                "ordering": ["-semester"],
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ukid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("relationship", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ManyToManyField(
                        related_name="guardians", to="student.student"
                    ),
                ),
            ],
            options={
                "db_table": "guardians",
                "ordering": ["first_name", "last_name"],
                "indexes": [
                    models.Index(fields=["email"], name="guardians_email_69eb1d_idx"),
                    models.Index(
                        fields=["phone_number"], name="guardians_phone_n_795ca1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ukid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("semester", models.CharField(max_length=20)),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                            ("suspended", "Suspended"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                            ("suspended", "Suspended"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="student.enrollment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_histories",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "db_table": "enrollment_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "created_at"],
                        name="enrollment__student_c353c2_idx",
                    ),
                    models.Index(
                        fields=["enrollment"], name="enrollment__enrollm_4ebcbf_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["program", "batch"], name="enrollments_program_0fa205_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "status"], name="enrollments_student_929bef_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "program", "semester")},
        ),
    ]
