# Generated by Django 5.2.8 on 2025-12-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
