# Generated by Django 5.2.8 on 2025-12-10 03:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("faculty", "__first__"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exam_code", models.CharField(max_length=20, unique=True)),
                ("exam_name", models.CharField(max_length=200)),
                (
                    "academic_year",
                    models.CharField(help_text="e.g., 2023-2024", max_length=20),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("fall", "Fall"),
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "duration_minutes",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "total_marks",
                    models.IntegerField(
                        default=100,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "passing_marks",
                    models.IntegerField(
                        default=40,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("midterm", "Midterm"),
                            ("final", "Final"),
                            ("quiz", "Quiz"),
                            ("practical", "Practical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("room_number", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Special instructions for students"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Whether results are published"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invigilator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invigilated_exams",
                        to="faculty.faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "db_table": "exams",
                "ordering": ["-exam_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marks_obtained",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        max_length=2,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("is_absent", models.BooleanField(default=False)),
                ("is_passed", models.BooleanField(default=False)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluated_results",
                        to="faculty.faculty",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Result",
                "verbose_name_plural": "Exam Results",
                "db_table": "exam_results",
                "ordering": ["-exam__exam_date", "student__first_name"],
            },
        ),
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("academic_year", models.CharField(max_length=20)),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("fall", "Fall"),
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_published", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Schedule",
                "verbose_name_plural": "Exam Schedules",
                "db_table": "exam_schedules",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["exam_code"], name="exams_exam_co_3911eb_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["status"], name="exams_status_863d01_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["exam_date"], name="exams_exam_da_14bdc1_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["academic_year", "semester"], name="exams_academi_3344e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["exam", "student"], name="exam_result_exam_id_007d8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(fields=["grade"], name="exam_result_grade_442ea1_idx"),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["is_passed"], name="exam_result_is_pass_3bc8da_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examresult",
            unique_together={("exam", "student")},
        ),
    ]
