# Generated by Django 5.2.8 on 2025-11-16 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=20)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("previous_school", models.CharField(max_length=255)),
                ("previous_grade", models.CharField(max_length=50)),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("program", models.CharField(db_index=True, max_length=100)),
                ("admission_year", models.IntegerField(db_index=True)),
                ("admission_semester", models.CharField(max_length=20)),
                (
                    "applicant_data",
                    models.JSONField(
                        default=dict, help_text="Additional applicant information"
                    ),
                ),
                (
                    "documents",
                    models.JSONField(
                        default=list, help_text="List of submitted documents"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("documents_pending", "Documents Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                            ("enrolled", "Enrolled"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "merit_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("rank", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "submitted_at"],
                        name="application_status_4711eb_idx",
                    ),
                    models.Index(
                        fields=["program", "admission_year"],
                        name="application_program_1f7a9d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MeritList",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("program", models.CharField(db_index=True, max_length=100)),
                ("admission_year", models.IntegerField(db_index=True)),
                ("admission_semester", models.CharField(max_length=20)),
                ("generation_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "criteria",
                    models.JSONField(
                        default=dict, help_text="Criteria used for merit calculation"
                    ),
                ),
                (
                    "ranked_applications",
                    models.JSONField(
                        default=list, help_text="List of ranked application IDs"
                    ),
                ),
                ("total_applications", models.IntegerField(default=0)),
                ("version", models.IntegerField(default=1)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("cutoff_rank", models.IntegerField(blank=True, null=True)),
                (
                    "cutoff_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "merit_lists",
                "ordering": ["-generation_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["program", "admission_year", "is_published"],
                        name="merit_lists_program_57b71d_idx",
                    )
                ],
                "unique_together": {
                    ("program", "admission_year", "admission_semester", "version")
                },
            },
        ),
    ]
