# Generated by Django 5.2.8 on 2025-12-10 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admissions_reviewed_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meritlist",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "submitted_at"], name="application_status_4711eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["program", "admission_year"],
                name="application_program_1f7a9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meritlist",
            index=models.Index(
                fields=["program", "admission_year", "is_published"],
                name="merit_lists_program_57b71d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meritlist",
            unique_together={
                ("program", "admission_year", "admission_semester", "version")
            },
        ),
    ]
