# Generated by Django 5.2.8 on 2025-11-17 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric_key",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("metric_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("computed_value", models.JSONField(default=dict)),
                ("last_refreshed", models.DateTimeField(auto_now=True)),
                (
                    "refresh_frequency",
                    models.IntegerField(
                        default=3600, help_text="Refresh frequency in seconds"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("admissions", "Admissions"),
                            ("attendance", "Attendance"),
                            ("finance", "Finance"),
                            ("courses", "Courses"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "analytics_dashboard_metrics",
                "ordering": ["category", "metric_key"],
                "indexes": [
                    models.Index(
                        fields=["metric_key"], name="analytics_d_metric__53c29b_idx"
                    ),
                    models.Index(
                        fields=["category"], name="analytics_d_categor_288c2e_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="analytics_d_is_acti_a50c43_idx"
                    ),
                ],
            },
        ),
    ]
