# Generated by Django 5.2.8 on 2025-12-10 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsQuery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("query_type", models.CharField(db_index=True, max_length=50)),
                (
                    "query_config",
                    models.JSONField(help_text="Query configuration and parameters"),
                ),
                (
                    "visualization_config",
                    models.JSONField(
                        default=dict, help_text="Chart/visualization settings"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Analytics Query",
                "verbose_name_plural": "Analytics Queries",
                "db_table": "analytics_queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_key",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("metric_name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="Category: admissions, attendance, finance, etc.",
                        max_length=50,
                    ),
                ),
                ("computed_value", models.JSONField(help_text="Computed metric data")),
                ("is_active", models.BooleanField(default=True)),
                ("last_computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dashboard Metric",
                "verbose_name_plural": "Dashboard Metrics",
                "db_table": "dashboard_metrics",
                "ordering": ["category", "metric_name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("admissions", "Admissions Report"),
                            ("attendance", "Attendance Report"),
                            ("academic", "Academic Performance Report"),
                            ("financial", "Financial Report"),
                            ("student", "Student Report"),
                            ("teacher", "Teacher Report"),
                            ("custom", "Custom Report"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Report generation parameters"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(default=dict, help_text="Applied filters"),
                ),
                (
                    "report_data",
                    models.JSONField(default=dict, help_text="Generated report data"),
                ),
                (
                    "file_path",
                    models.FileField(blank=True, null=True, upload_to="reports/%Y/%m/"),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("json", "JSON"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "schedule_frequency",
                    models.CharField(
                        blank=True, help_text="daily, weekly, monthly", max_length=50
                    ),
                ),
                ("next_run", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "analytics_reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
